/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'issuer' : string,
  'credentialUrl' : [] | [string],
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'repoUrl' : [] | [string],
  'liveUrl' : [] | [string],
  'techStack' : Array<string>,
}
export interface _SERVICE {
  'addCertification' : ActorMethod<
    [string, string, string, [] | [string]],
    Certification
  >,
  'addProject' : ActorMethod<
    [string, string, Array<string>, [] | [string], [] | [string]],
    Project
  >,
  'getAllCertifications' : ActorMethod<[], Array<Certification>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCertification' : ActorMethod<[bigint], Certification>,
  'getProject' : ActorMethod<[bigint], Project>,
  'seedData' : ActorMethod<[], undefined>,
  'updateCertification' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    Certification
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, Array<string>, [] | [string], [] | [string]],
    Project
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];