/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Certification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'issuer' : IDL.Text,
  'credentialUrl' : IDL.Opt(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'repoUrl' : IDL.Opt(IDL.Text),
  'liveUrl' : IDL.Opt(IDL.Text),
  'techStack' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addCertification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Certification],
      [],
    ),
  'addProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Project],
      [],
    ),
  'getAllCertifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCertification' : IDL.Func([IDL.Nat], [Certification], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'seedData' : IDL.Func([], [], []),
  'updateCertification' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Certification],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Project],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Certification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'issuer' : IDL.Text,
    'credentialUrl' : IDL.Opt(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'repoUrl' : IDL.Opt(IDL.Text),
    'liveUrl' : IDL.Opt(IDL.Text),
    'techStack' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addCertification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Certification],
        [],
      ),
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Project],
        [],
      ),
    'getAllCertifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCertification' : IDL.Func([IDL.Nat], [Certification], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'seedData' : IDL.Func([], [], []),
    'updateCertification' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Certification],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Project],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };