/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Project {
    id: bigint;
    title: string;
    description: string;
    repoUrl?: string;
    liveUrl?: string;
    techStack: Array<string>;
}
export interface Certification {
    id: bigint;
    title: string;
    date: string;
    issuer: string;
    credentialUrl?: string;
}
export interface backendInterface {
    addCertification(title: string, issuer: string, date: string, credentialUrl: string | null): Promise<Certification>;
    addProject(title: string, description: string, techStack: Array<string>, liveUrl: string | null, repoUrl: string | null): Promise<Project>;
    getAllCertifications(): Promise<Array<Certification>>;
    getAllProjects(): Promise<Array<Project>>;
    getCertification(id: bigint): Promise<Certification>;
    getProject(id: bigint): Promise<Project>;
    seedData(): Promise<void>;
    updateCertification(id: bigint, title: string, issuer: string, date: string, credentialUrl: string | null): Promise<Certification>;
    updateProject(id: bigint, title: string, description: string, techStack: Array<string>, liveUrl: string | null, repoUrl: string | null): Promise<Project>;
}
import type { Certification as _Certification, Project as _Project } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCertification(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Certification> {
        if (this.processError) {
            try {
                const result = await this.actor.addCertification(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCertification(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProject(arg0: string, arg1: string, arg2: Array<string>, arg3: string | null, arg4: string | null): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCertifications(): Promise<Array<Certification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCertifications();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCertifications();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertification(arg0: bigint): Promise<Certification> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertification(arg0);
                return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertification(arg0);
            return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async updateCertification(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<Certification> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCertification(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCertification(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Certification_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: string | null, arg5: string | null): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Certification_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certification): Certification {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: string;
    issuer: string;
    credentialUrl: [] | [string];
}): {
    id: bigint;
    title: string;
    date: string;
    issuer: string;
    credentialUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        issuer: value.issuer,
        credentialUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.credentialUrl))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    repoUrl: [] | [string];
    liveUrl: [] | [string];
    techStack: Array<string>;
}): {
    id: bigint;
    title: string;
    description: string;
    repoUrl?: string;
    liveUrl?: string;
    techStack: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        repoUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.repoUrl)),
        liveUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.liveUrl)),
        techStack: value.techStack
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Certification>): Array<Certification> {
    return value.map((x)=>from_candid_Certification_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n5(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
